mod album_detail;
mod albums;
mod artist_detail;
mod artists;
mod favorites;
mod home;
mod playlist_detail;
mod playlists;
mod queue;
mod radio;
mod random;
mod search;
mod settings;
mod stats;

pub use album_detail::AlbumDetailView;
pub use albums::AlbumsView;
pub use artist_detail::ArtistDetailView;
pub use artists::ArtistsView;
pub use favorites::FavoritesView;
pub use home::HomeView;
pub use playlist_detail::PlaylistDetailView;
pub use playlists::PlaylistsView;
pub use queue::QueueView;
pub use radio::RadioView;
pub use random::RandomView;
pub use search::SearchView;
pub use settings::SettingsView;
pub use stats::StatsView;
